import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Dashboard from './Dashboard/index'

export default function Home () {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;600;700&display=swap')
        </style>
      </Head>

      <main className={styles.content}>
        <Dashboard />
      </main>
    </div>
  )
}
